apiVersion: v1
data:
  config: |
    ldap:
      addr: ldap://192.168.3.81:389
      adminUser: xxxxx
      adminPwd: xxxxxx
      baseDN: dc=corp,dc=xxx,dc=com
      filter: (&(objectClass=person)(sAMAccountName=%s))
      attributes: user_dn
      orgUnitName: OU=
    rbac:
      DevOps team:
        sa: admin
        ns: kube-system
      wangweilei:
        sa: wwl-admin
        ns: default
      xupeng:
        sa: search-admin
        ns: default
    clusters:
      local:
        apiServer: apiserver-dev.jiunile.com
        port: 443
        dashboard: dashboard-dev.jiunile.com
        desc: Dev Cluster
      cnrelease:
        apiServer: apiserver-cn-release.jiunile.com
        port: 443
        dashboard: dashboard-cn-release.jiunile.com
        desc: CN Release Cluster
      usrelease:
        apiServer: apiserver-us-release.jiunile.com
        port: 443
        dashboard: dashboard-us-release.jiunile.com
        desc: US Release Cluster
      euprod:
        apiServer: apiserver-eu-prod.jiunile.com
        port: 443
        dashboard: dashboard-eu-prod.jiunile.com
        desc: EU Prod Cluster
kind: ConfigMap
metadata:
  name: mutiboard-ldap
  namespace: kube-system
